-- ============================================================================
-- Procedure : SP_CUSTOMER_SCD2
-- Source map: m_customer_scd2_enterprise (Sample_3_Mapping.xml)
-- Pattern   : Slowly Changing Dimension Type 2 (Insert + Update)
--
-- Transformation pipeline mapped to SQL:
--   SQ_STG_CUSTOMERS -> custom SELECT: STG_CUSTOMERS JOIN STG_REGIONS, EMAIL IS NOT NULL
--   LKP_Dim_Customer -> LEFT JOIN DIM_CUSTOMER (IS_ACTIVE='Y') ON CUSTOMER_ID
--   EXP_SCD_Logic    -> V_CURRENT_HASH = MD5(...); new/changed flags
--   RTR_SCD_Rows     -> INSERT_NEW / INSERT_UPDATE / UPDATE_OLD
--   UPD_Old_Version  -> UPDATE expire (IS_ACTIVE='N', EFF_END_DATE)
--   SEQ_Cust_Key     -> CUSTOMER_SK AUTOINCREMENT on the table
--
-- SCD2 state logic (BR-4..BR-6):
--   not found            -> INSERT new (IS_ACTIVE='Y')
--   found, hash matches  -> SKIP (no action)
--   found, hash differs  -> expire old (IS_ACTIVE='N') + INSERT new version
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_CUSTOMER_SCD2()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    rows_expired  INTEGER DEFAULT 0;
    rows_inserted INTEGER DEFAULT 0;
    load_ts       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    -- Staged source with current hash and the active-row lookup result.
    CREATE OR REPLACE TEMPORARY TABLE TMP_SCD_SRC AS
    SELECT
        src.CUSTOMER_ID,
        src.CUSTOMER_NAME,
        src.ADDRESS,
        src.PHONE,
        src.TIER,
        -- EXP_SCD_Logic: V_CURRENT_HASH (BR-2, columns: ADDRESS, PHONE, TIER)
        MD5(COALESCE(src.ADDRESS, '') || '||' || COALESCE(src.PHONE, '') || '||' || COALESCE(src.TIER, '')) AS ROW_HASH,
        d.CUSTOMER_SK    AS LKP_CUSTOMER_SK,
        d.ROW_HASH_MD5   AS LKP_ROW_HASH_MD5,
        -- O_IS_NEW_RECORD / O_IS_CHANGED_RECORD
        IFF(d.CUSTOMER_SK IS NULL, 1, 0) AS IS_NEW_RECORD,
        IFF(d.CUSTOMER_SK IS NOT NULL
            AND MD5(COALESCE(src.ADDRESS, '') || '||' || COALESCE(src.PHONE, '') || '||' || COALESCE(src.TIER, '')) <> d.ROW_HASH_MD5,
            1, 0) AS IS_CHANGED_RECORD
    FROM (
        SELECT stg.CUSTOMER_ID, stg.CUSTOMER_NAME, stg.ADDRESS, stg.PHONE, stg.TIER
        FROM STG_CUSTOMERS stg
        INNER JOIN STG_REGIONS r ON stg.REGION_ID = r.REGION_ID   -- BR-1 (valid region)
        WHERE stg.EMAIL IS NOT NULL                               -- BR-1 (non-NULL email)
    ) src
    LEFT JOIN DIM_CUSTOMER d
        ON d.CUSTOMER_ID = src.CUSTOMER_ID
       AND d.IS_ACTIVE = 'Y';

    -- UPD_Old_Version: expire the current version of changed customers FIRST
    -- (must run before the insert so the active-row uniqueness holds).
    UPDATE DIM_CUSTOMER
    SET IS_ACTIVE = 'N',
        EFF_END_DATE = :load_ts
    FROM TMP_SCD_SRC s
    WHERE DIM_CUSTOMER.CUSTOMER_ID = s.CUSTOMER_ID
      AND DIM_CUSTOMER.IS_ACTIVE = 'Y'
      AND s.IS_CHANGED_RECORD = 1;
    rows_expired := SQLROWCOUNT;

    -- INSERT_NEW + INSERT_UPDATE: insert active versions for new and changed rows.
    -- CUSTOMER_SK is auto-generated by the AUTOINCREMENT column (SEQ_Cust_Key).
    INSERT INTO DIM_CUSTOMER
        (CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE, TIER,
         ROW_HASH_MD5, IS_ACTIVE, EFF_START_DATE, EFF_END_DATE, LOAD_TIMESTAMP)
    SELECT
        CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE, TIER,
        ROW_HASH, 'Y', :load_ts, NULL, :load_ts
    FROM TMP_SCD_SRC
    WHERE IS_NEW_RECORD = 1
       OR IS_CHANGED_RECORD = 1;
    rows_inserted := SQLROWCOUNT;

    RETURN 'SP_CUSTOMER_SCD2: expired ' || rows_expired
        || ' old version(s), inserted ' || rows_inserted || ' active version(s).';
END;
$$;
